name: Waka Readme

on:
  schedule:
    # Runs every 2 hours
    - cron: '0 */2 * * *'
  #workflow_dispatch:
jobs:
  update-readme:
    name: Update Readme with Metrics
    runs-on: ubuntu-latest
    steps:
      - uses: anmol098/waka-readme-stats@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          SHOW_COMMIT: "True"
          SHOW_DAYS_OF_WEEK: "True"
          #SHOW_LANGUAGE: "False"
          #SHOW_OS: "False"
          #SHOW_PROJECTS: "True"
          SHOW_LINES_OF_CODE: "True"
          #SHOW_TIMEZONE: "False"
          #SHOW_EDITORS: "False"
          #SHOW_LANGUAGE_PER_REPO: "False"
          #LOCALE: "es"
