name: Waka Readme
#https://github.com/anmol098/waka-readme-stats

on:
  workflow_dispatch:
  schedule:
    # Runs at 12am
    - cron: '30 18 * * *'
  pull_request:
    branches:
      - main

jobs:
  update-readme:
    name: Update Readme with Metrics
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: AyushAgnihotri2025/waka-readme-stats@master # anmol098/waka-readme-stats@fix/repositories_filtering #master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          SHOW_COMMIT: "True"
          SHOW_LINES_OF_CODE: "False"
          SHOW_PROFILE_VIEWS: "False"
          SHOW_DAYS_OF_WEEK: "True"
          SHOW_LANGUAGE: "False"
          SHOW_OS: "False"
          SHOW_PROJECTS: "False"
          SHOW_TIMEZONE: "False"
          SHOW_EDITORS: "False"
          SHOW_SHORT_INFO: "False"
          SHOW_LOC_CHART: "False"
          SHOW_LANGUAGE_PER_REPO: "False"
          LOCALE: "es"
